language: python

python:
  - "3.6.5"

addons:
  postgresql: '9.6'

services:
  - postgresql
  
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

before_script:
  - psql -c "create database storemanager;" -U postgres

script:
  - nosetests --with-cov --cov  tests/
  
after_success:
  - codecov
  - coveralls
